[project]
name = "cancan"
version = "0.1.0"
description = "A minimalistic data pipeline for open datasets"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
